# Load local env files when running with Maven (Spring does not read .env automatically).
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=api-service
server.port=${SERVER_PORT:8080}

# spring.datasource.url=${POSTGRES_JDBC_DB_URL}
# spring.datasource.username=${API_DB_USER}
# spring.datasource.password=${API_DB_PASSWORD}

spring.datasource.url=${DB_URL:${POSTGRES_JDBC_DB_URL}}
spring.datasource.username=${DB_USER:${API_DB_USER}}
spring.datasource.password=${DB_PASSWORD:${API_DB_PASSWORD}}

# spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.tool.schema=DEBUG
# spring.jpa.show-sql=true

spring.data.rest.base-path=/api
