spring.application.name=api-service
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/newsdibi}
spring.datasource.username=${DB_USER:${API_DB_USER:api_service_user}}
spring.datasource.password=${DB_PASSWORD:${API_DB_PASSWORD:change_me_api_service}}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta


spring.data.rest.base-path=/api
