services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NEWS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-newsdibi}"]
      interval: 10s
      timeout: 5s
      retries: 5

  newsapi-service:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    container_name: newsapi-service
    hostname: newsapi-service
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - DB_URL=${POSTGRES_JDBC_DB_URL}
      - DB_USER=${API_DB_USER}
      - DB_PASSWORD=${API_DB_PASSWORD}
      - JPA_DDL_AUTO=validate
      - TZ=Asia/Jakarta
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
